<?php
/**
 * Copyright © 2022 Chazki. All rights reserved.
 *
 * @category Class
 * @package  Chazki_ChazkiArg
 * @author   Chazki
 */
?>
<?php /** @var Chazki\ChazkiArg\Block\ReferenceAddress $block */ ?>
<?php $reference_address = $block->getAddress()->getCustomAttribute('reference_address'); ?>
<?php if (isset($reference_address)): ?>
    <?php $reference_address = $reference_address->getValue(); ?>
<?php endif; ?>

<div class="field">
    <label class="label" for="new_field"><?php echo __('Reference Address') ?></label>
    <label>
        <input type="text"
               name="reference_address"
               value="<?= $block->escapeHtmlAttr($reference_address ?? '') ?>"
        />
    </label>
</div>
