<?php
/**
 * Copyright © 2022 Chazki. All rights reserved.
 *
 * @category Class
 * @package  Chazki_ChazkiArg
 * @author   Chazki
 */
?>
<?php /** @var Chazki\ChazkiArg\Block\RucNumber $block */ ?>
<?php $rucNumber = $block->getAddress()->getCustomAttribute('ruc_number'); ?>
<?php if (isset($rucNumber)): ?>
    <?php $rucNumber = $rucNumber->getValue(); ?>
<?php endif; ?>

<div class="field">
    <label class="label" for="new_field"><?php echo __('Ruc Number') ?></label>
    <label>
        <input type="text"
               name="ruc_number"
               value="<?= $block->escapeHtmlAttr($rucNumber ?? '') ?>"
        />
    </label>
</div>
